### ISSUE TITLE
Gas limit set dangerously high. Approving this transaction is likely to fail.

### ISSUE THREAD

**Issue by kolsan789** [hunterlong/ethereum-ico-contract#1]
Hi,

I deployed the tokens (Sale and Token) from my Account2 via Remix online compiler but when I try to send some ethers from my Account1 to the Sale contract I get in MetaMask:
"Gas limit set dangerously high. Approving this transaction is likely to fail." And the transaction really fails.
Any idea what might be wrong?

I am using Ropsten Testnet

**Comment by shaharsol** [comment]
same here, via ethereum wallet

![screen shot 2018-02-22 at 3 18 34 pm](https://user-images.githubusercontent.com/672778/36540622-c40efb6a-17e3-11e8-9d55-307ce3c1dc0e.png)

**Comment by hunterlong** [comment]
Hey, sorry for the late response. Looks like there needs to be some updates, but the ICO creation process did work for me. You guys aren't giving any ether to the contribute function. Its not fun to run a free ICO! Send ETH with contribute and the transaction should pass. I just ran the entire process, here it is:

1. I created the Sale contract first. Ropsten contract: [0x21afa0e1605bb3f34407b466b89ecb0bdee1cf30](https://ropsten.etherscan.io/address/0x21afa0e1605bb3f34407b466b89ecb0bdee1cf30)

2. Then I created the Token contract, and I included the Sale contract address when I created it. The Token contract requires the Sale contract. [0x5c12a35db341ef86c6e9d5073f62950e10c3559d](https://ropsten.etherscan.io/token/0x5c12a35db341ef86c6e9d5073f62950e10c3559d)

3. Once I have both Token and Sale contract live, I run the `setup(token_address, ending_block)` function to the Sale contract. [0x3afa67b0e5d98ba3064db5c6bcfd0d64b46607a7d602ad80caca5bbb6a297654](https://ropsten.etherscan.io/tx/0x3afa67b0e5d98ba3064db5c6bcfd0d64b46607a7d602ad80caca5bbb6a297654) This locks everything and you will not be able to setup again.

4. Everything is all setup! Let the ICO begin! I can now send the `contribute` function with an amount of ETH. If you send 0 ETH it will fail! I sent 1 ETH with data `0xd7bb99ba` to the Sale contract. [0x1a2432f1caac0ed18df3aeace78db7c054a2c1b06fb5d20d4376c3f4a44365e2](https://ropsten.etherscan.io/tx/0x1a2432f1caac0ed18df3aeace78db7c054a2c1b06fb5d20d4376c3f4a44365e2)

**It worked!** You can see in the contribute transaction the 1 ETH I sent was forwarded to my ETH holding wallet address. You can also see I received 600 tokens! This ICO will be running till block 7 million, so feel free to contribute to the testnet ICO!

**Comment by hunterlong** [comment]
I just updated the contracts and npm packages to newest version of truffle. I also added a Deployment tutorial with examples of transactions and contracts on the readme. This should clear the confusion. :moneybag:
