### ISSUE TITLE
how can i know method signature

### ISSUE THREAD

**Issue by Bo3o2S** [hunterlong/ethereum-ico-contract#2]
i really appreciate for this good example of ico contract.
i just have a question about how can i know method signature.
i recognized that you use '0xd7bb99ba ' as a payable signature
and it makes walking 'contribute()' and it can be exchange Token.
but this time i just wonder if i make a new function for payable function,
how can i know method signature?

**Comment by hunterlong** [comment]
hey @Bo3o2S, i recently updated the code to allow contributions **without** sending the `0xd7bb99ba` as data. The default function will run the contribute process as long as you send ETH and enough gas, I estimated gas limit should be set to 100,000 to make sure transactions are processed. [Default function](https://github.com/hunterlong/ethereum-ico-contract/blob/master/contracts/Sale.sol#L76)

**Comment by hunterlong** [comment]
Also, to get the bytecode to a function, you can use Remix. Remix can compile your code and give you an easy to use UI for creating ethereum smart contracts. Checkout the [remix gist link](https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.21+commit.dfe3193c.js&gist=77e6367a051a3b27d8431cad4caf275a) and can compile from within your browser!
